service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  profile: sandx

plugins:
  - serverless-webpack
  - serverless-openapi-documenter

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    excludeFiles: src/**/*.test.js
  documentation: ${file(serverless.doc.yml):documentation}

functions:
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true
          documentation:
            summary: Return product by ID
            description: OK
            pathParams:
              - name: productId
                description: Product Id
                schema:
                  type: string
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: Product object
                responseModels:
                  application/json: GetProductByIdResponse
              - statusCode: 404
                responseBody:
                  description: Product not found
                responseModels:
                  application/json: GetProductByIdErrorResponse

  getAllProducts:
    handler: handler.getAllProducts
    events:
      - http:
          path: products
          method: get
          cors: true
          documentation:
            summary: Return list of products
            description: OK
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: List of products
                responseModels:
                  application/json: GetAllProductsResponse
