service: import-service
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  profile: sandx
  environment:
    REGION: ${self:custom.region}
    BUCKET: ${self:custom.bucket}
    SQS_URL: ${self:custom.sqsUrl}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"
        - Effect: Allow
          Action:
            - 'logs:CreateLogGroup'
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
          Resource: 'arn:aws:logs:*:*:*'
        - Effect: Allow
          Action:
            - "sqs:SendMessage"
          Resource: arn:aws:sqs:${aws:region}:${aws:accountId}:${self:custom.sqsName}

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    excludeFiles: src/**/*.test.js
    includeModules:
      forceInclude:
        - csv-parser
  bucket: ${env:BUCKET}
  region: ${env:REGION}
  sqsName: catalogItemsQueue.fifo
  sqsUrl: https://sqs.${self:custom.region}.amazonaws.com/${aws:accountId}/${self:custom.sqsName}

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          # authorizer:
          #   type: token
          #   name: basicAuthorizer
          #   arn: arn:aws:lambda:${self:custom.region}:${aws:accountId}:function:authorization-service-dev-basicAuthorizer
          #   resultTtlInSeconds: 0
          #   identitySource: method.request.header.Authorization
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          event: s3:ObjectCreated:*
          bucket: ${self:custom.bucket}
          existing: true
          rules:
            - prefix: uploaded/

resources:
  Resources:
    # Unauthorized:
    #   Type: AWS::ApiGateway::GatewayResponse
    #   Properties:
    #     ResponseParameters:
    #       "gatewayresponse.header.Access-Control-Allow-Origin": "'*'"
    #       "gatewayresponse.header.Access-Control-Allow-Headers": "'*'"
    #     ResponseType: "DEFAULT_4XX"
    #     RestApiId:
    #       Ref: "ApiGatewayRestApi"
    Uploads:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "Authorization"
              AllowedMethods:
                - GET
              AllowedOrigins:
                - "*"
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - PUT
              AllowedOrigins:
                - "*"
